# Generated by Django 2.0.3 on 2018-07-29 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsuplier',
            name='curent_sum',
        ),
    ]
