# Generated by Django 2.0.3 on 2018-08-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productsuplier_curent_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='techdescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
