# Generated by Django 2.0.3 on 2018-08-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_techdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='complectation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
