# Generated by Django 2.0.3 on 2018-08-16 10:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_complectation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=Decimal('0'), validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='quantity',
            field=models.IntegerField(default=Decimal('99999'), validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
