# Generated by Django 2.0.3 on 2018-07-27 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('facebook', 'Facebook-Oauth2'), ('google-oauth2', 'Google-Oauth2')], max_length=20)),
                ('key', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('include_taxes_in_prices', models.BooleanField(default=True)),
                ('display_gross_prices', models.BooleanField(default=True)),
                ('charge_taxes_on_shipping', models.BooleanField(default=True)),
                ('track_inventory_by_default', models.BooleanField(default=True)),
                ('bottom_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menu.Menu')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='sites.Site')),
                ('top_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menu.Menu')),
            ],
            options={
                'permissions': (('edit_settings', 'Can edit site settings'), ('view_settings', 'Can view site settings')),
            },
        ),
        migrations.AddField(
            model_name='authorizationkey',
            name='site_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site.SiteSettings'),
        ),
        migrations.AlterUniqueTogether(
            name='authorizationkey',
            unique_together={('site_settings', 'name')},
        ),
    ]
