# Generated by Django 2.0.3 on 2018-07-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('unfulfilled', 'Не оплачено'), ('partially fulfilled', 'Частично оплачено'), ('fulfilled', 'Оплачено'), ('canceled', 'Отменено')], default='unfulfilled', max_length=32),
        ),
        migrations.AlterField(
            model_name='suplierorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('unfulfilled', 'Не оплачено'), ('partially fulfilled', 'Частично оплачено'), ('fulfilled', 'Оплачено'), ('canceled', 'Отменено')], default='current', max_length=32),
        ),
    ]
