# Generated by Django 2.0.3 on 2018-08-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20180731_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='complectation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
