# Generated by Django 2.0.3 on 2018-08-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180815_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery_address',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
